[package]
name = "sinter_themes"
version = "0.1.0"
edition = "2024"

[dependencies]
sinter_theme_sdk = { path = "../sinter_theme_sdk" }
sinter_default_theme = { path = "packages/default_theme" }
sinter_default_theme_light = { path = "packages/default_theme_light" }