[[theme]]
name = "default"
path = "packages/default_theme"
pre_build_cmd = "npm install"
build_cmd = "npm run build"
css_path = "style"
files = ["default.css", "output.css", "aurora.css", "liquid.css"]

[[theme]]
name = "default_light"
path = "packages/default_theme_light"
pre_build_cmd = "npm install"
build_cmd = "npm run build"
css_path = "style"
files = ["default.css", "output.css", "aurora.css", "liquid.css"]
