[package]
name = "sinter_default_theme_light"
version = "0.1.0"
edition = "2024"

[dependencies]
sinter_core = { path = "../../../sinter_core" }
sinter_ui = { path = "../../../sinter_ui" }
sinter_theme_sdk = { path = "../../../sinter_theme_sdk" }
